### PR TITLE
[Aggregator] Fix Initialization of Aggregator Factory

### LINKED ISSUE #284: Initialization of Aggregator Factory Not Work Properly for the Second Time
The initialization of aggregator factory uses `call_once` to initialize some globally shared variables. When we terminate all the worker threads and create a new group of worker threads, the `call_once` fails to refresh its state and thus the initialization of aggregator factory fails for the second time.

This can be fixed by simply using std::mutex.

### PR DESCRIPTION
**Pull request by zzxx-husky**
Fix #284

Remove call_once. Use std::mutex for the initialization of aggregator factory and that that works properly for the second initialization.

### CODE REVIEW

**Comment by kygx-legend** [comment]
If there's a concrete test case which can reproduce this problem, it's better.

**Comment by zzxx-husky** [comment]
@kygx-legend The problem could be easily reproduced in pyhusky, by submitting one job after another and the two jobs both need to use aggregator. In C++ Husky, I found it difficult to reproduce. @x@

**Comment by kygx-legend** [comment]
@zzxx-husky I see.

**Comment by kygx-legend** [comment]
Any problem for this PR?

File: lib/aggregator.hpp [hunk 1]
```diff
@@ -175,6 +176,7 @@ class AggregatorFactoryBase {
     InnerSharedData* shared_data_{nullptr};
 
     static thread_local std::shared_ptr<AggregatorFactoryBase> factory_;
+    static std::mutex shared_mutex_;
```
Comment (kygx-legend) [inline lib/aggregator.hpp]: `s/shared_mutex_/s_shared_mutex`

**Comment by zzxx-husky** [comment]
@kygx-legend I forget to follow up. Should have no problem. I have also updated the names of the static variables.

**Comment by kygx-legend** [comment]
LGTM then. Thanks!
